<?php
	$index=$_REQUEST["userID"];
	
	$json1='[{
				"src":"images/img-nav/logo-001.png","name":"夏凉"
			},{
				"src":"images/img-nav/logo-002.png","name":"床品件套"
			},{
				"src":"images/img-nav/logo-003.png","name":"被枕"
			},{
				"src":"images/img-nav/logo-004.png","name":"家具"
			},{
				"src":"images/img-nav/logo-005.png","name":"收纳"
			},{
				"src":"images/img-nav/logo-006.png","name":"布艺软装"
			},{
				"src":"images/img-nav/logo-007.png","name":"家饰"
			},{
				"src":"images/img-nav/logo-008.png","name":"宠物"
			}]';
	$json2='[{
				"src":"images/img-nav/logo-101.png","name":"行李箱"
			},{
				"src":"images/img-nav/logo-102.png","name":"男士包袋"
			},{
				"src":"images/img-nav/logo-103.png","name":"女士包袋"
			},{
				"src":"images/img-nav/logo-104.png","name":"钱包小皮件"
			},{
				"src":"images/img-nav/logo-105.png","name":"女鞋"
			},{
				"src":"images/img-nav/logo-106.png","name":"男鞋"
			},{
				"src":"images/img-nav/logo-107.png","name":"拖鞋"
			},{
				"src":"images/img-nav/logo-108.png","name":"鞋配"
			},{
				"src":"images/img-nav/logo-109.png","name":"袜子"
			},{
				"src":"images/img-nav/logo-110.png","name":"丝袜"
			},{
				"src":"images/img-nav/logo-111.png","name":"配饰"
			},{
				"src":"images/img-nav/logo-112.png","name":"眼镜"
			},{
				"src":"images/img-nav/logo-113.png","name":"围巾件套"
			},{
				"src":"images/img-nav/logo-114.png","name":"旅行用品"
			}]';
	$json3='[{
				"src":"images/img-nav/logo-201.png","name":"行李箱"
			},{
				"src":"images/img-nav/logo-202.png","name":"男士包袋"
			},{
				"src":"images/img-nav/logo-203.png","name":"女士包袋"
			},{
				"src":"images/img-nav/logo-204.png","name":"钱包小皮件"
			},{
				"src":"images/img-nav/logo-205.png","name":"女鞋"
			},{
				"src":"images/img-nav/logo-206.png","name":"男鞋"
			},{
				"src":"images/img-nav/logo-207.png","name":"拖鞋"
			},{
				"src":"images/img-nav/logo-208.png","name":"鞋配"
			},{
				"src":"images/img-nav/logo-209.png","name":"袜子"
			},{
				"src":"images/img-nav/logo-210.png","name":"丝袜"
			},{
				"src":"images/img-nav/logo-211.png","name":"配饰"
			},{
				"src":"images/img-nav/logo-212.png","name":"眼镜"
			}]';
	$json4='[{
				"src":"images/img-nav/logo-301.png","name":"行李箱"
			},{
				"src":"images/img-nav/logo-302.png","name":"男士包袋"
			},{
				"src":"images/img-nav/logo-303.png","name":"女士包袋"
			},{
				"src":"images/img-nav/logo-304.png","name":"钱包小皮件"
			},{
				"src":"images/img-nav/logo-305.png","name":"女鞋"
			}]';
	$json5='[{
				"src":"images/img-nav/logo-401.png","name":"行李箱"
			},{
				"src":"images/img-nav/logo-402.png","name":"男士包袋"
			},{
				"src":"images/img-nav/logo-403.png","name":"女士包袋"
			},{
				"src":"images/img-nav/logo-404.png","name":"钱包小皮件"
			},{
				"src":"images/img-nav/logo-405.png","name":"女鞋"
			},{
				"src":"images/img-nav/logo-406.png","name":"男鞋"
			},{
				"src":"images/img-nav/logo-407.png","name":"拖鞋"
			},{
				"src":"images/img-nav/logo-408.png","name":"鞋配"
			},{
				"src":"images/img-nav/logo-409.png","name":"袜子"
			},{
				"src":"images/img-nav/logo-410.png","name":"丝袜"
			}]';
	$json6='[{
				"src":"images/img-nav/logo-501.png","name":"行李箱"
			},{
				"src":"images/img-nav/logo-502.png","name":"男士包袋"
			},{
				"src":"images/img-nav/logo-503.png","name":"女士包袋"
			},{
				"src":"images/img-nav/logo-504.png","name":"钱包小皮件"
			},{
				"src":"images/img-nav/logo-505.png","name":"女鞋"
			},{
				"src":"images/img-nav/logo-506.png","name":"男鞋"
			},{
				"src":"images/img-nav/logo-507.png","name":"拖鞋"
			},{
				"src":"images/img-nav/logo-508.png","name":"鞋配"
			},{
				"src":"images/img-nav/logo-509.png","name":"袜子"
			},{
				"src":"images/img-nav/logo-510.png","name":"丝袜"
			},{
				"src":"images/img-nav/logo-511.png","name":"配饰"
			},{
				"src":"images/img-nav/logo-512.png","name":"眼镜"
			}]';
	$json7='[{
				"src":"images/img-nav/logo-601.png","name":"行李箱"
			},{
				"src":"images/img-nav/logo-602.png","name":"男士包袋"
			},{
				"src":"images/img-nav/logo-603.png","name":"女士包袋"
			},{
				"src":"images/img-nav/logo-604.png","name":"钱包小皮件"
			},{
				"src":"images/img-nav/logo-605.png","name":"女鞋"
			},{
				"src":"images/img-nav/logo-606.png","name":"男鞋"
			},{
				"src":"images/img-nav/logo-607.png","name":"拖鞋"
			}]';
	$json8='[{
				"src":"images/img-nav/logo-701.png","name":"行李箱"
			},{
				"src":"images/img-nav/logo-702.png","name":"男士包袋"
			},{
				"src":"images/img-nav/logo-703.png","name":"女士包袋"
			},{
				"src":"images/img-nav/logo-704.png","name":"钱包小皮件"
			},{
				"src":"images/img-nav/logo-705.png","name":"女鞋"
			},{
				"src":"images/img-nav/logo-706.png","name":"男鞋"
			},{
				"src":"images/img-nav/logo-707.png","name":"拖鞋"
			},{
				"src":"images/img-nav/logo-708.png","name":"鞋配"
			},{
				"src":"images/img-nav/logo-709.png","name":"袜子"
			}]';
	$json9='[{
				"src":"images/img-nav/logo-801.png","name":"行李箱"
			},{
				"src":"images/img-nav/logo-802.png","name":"男士包袋"
			},{
				"src":"images/img-nav/logo-803.png","name":"女士包袋"
			},{
				"src":"images/img-nav/logo-804.png","name":"钱包小皮件"
			},{
				"src":"images/img-nav/logo-805.png","name":"女鞋"
			},{
				"src":"images/img-nav/logo-806.png","name":"男鞋"
			},{
				"src":"images/img-nav/logo-807.png","name":"拖鞋"
			},{
				"src":"images/img-nav/logo-808.png","name":"鞋配"
			},{
				"src":"images/img-nav/logo-809.png","name":"袜子"
			},{
				"src":"images/img-nav/logo-810.png","name":"丝袜"
			},{
				"src":"images/img-nav/logo-811.png","name":"配饰"
			},{
				"src":"images/img-nav/logo-812.png","name":"眼镜"
			},{
				"src":"images/img-nav/logo-813.png","name":"眼镜"
			}]';
	$json10='[{
				"src":"images/img-nav/logo-901.png","name":"行李箱"
			},{
				"src":"images/img-nav/logo-902.png","name":"男士包袋"
			},{
				"src":"images/img-nav/logo-903.png","name":"女士包袋"
			},{
				"src":"images/img-nav/logo-904.png","name":"钱包小皮件"
			},{
				"src":"images/img-nav/logo-905.png","name":"女鞋"
			},{
				"src":"images/img-nav/logo-906.png","name":"男鞋"
			},{
				"src":"images/img-nav/logo-907.png","name":"拖鞋"
			},{
				"src":"images/img-nav/logo-908.png","name":"鞋配"
			},{
				"src":"images/img-nav/logo-909.png","name":"袜子"
			},{
				"src":"images/img-nav/logo-910.png","name":"丝袜"
			}]';
	
	
	if($index==1){ echo $json1;}
	if($index==2){ echo $json2;}
	if($index==3){ echo $json3;}
	if($index==4){ echo $json4;}
	if($index==5){ echo $json5;}
	if($index==6){ echo $json6;}
	if($index==7){ echo $json7;}
	if($index==8){ echo $json8;}
	if($index==9){ echo $json9;}
	if($index==10){ echo $json10;}
	
?>