<?php
	$json1='[{
			"src":"images/img-show/show-001.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-002.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-003.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-004.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-005.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-006.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-007.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-008.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		}]';
	$json2='[{
			"src":"images/img-show/show-101.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-102.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-103.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-104.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-105.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-106.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-107.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-108.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		}]';
	$json3='[{
			"src":"images/img-show/show-201.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-202.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-203.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-204.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-205.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-206.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-207.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-208.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		}]';
	$json4='[{
			"src":"images/img-show/show-301.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-302.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-303.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-304.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-305.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-306.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-307.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-308.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		}]';
	$json5='[{
			"src":"images/img-show/show-401.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-402.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-403.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-404.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-405.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-406.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-407.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-408.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		}]';
	$json6='[{
			"src":"images/img-show/show-501.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-502.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-503.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-504.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-505.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-506.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-507.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-508.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		}]';
	$json7='[{
			"src":"images/img-show/show-601.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-602.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-603.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-604.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-605.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-606.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-607.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		},{
			"src":"images/img-show/show-608.png",
			"msg1":"再生纸双环笔记本",
			"price":"￥19.9",
			"msg2":"无荧光纸张，记事必备"
		}]';

	$index=$_REQUEST["userID"];
	if($index==1){ echo $json1;}
	if($index==2){ echo $json2;}
	if($index==3){ echo $json3;}
	if($index==4){ echo $json4;}
	if($index==5){ echo $json5;}
	if($index==6){ echo $json6;}
	if($index==7){ echo $json7;}

?>